import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'happy-dom',
    setupFiles: ['./src/test/setup.ts'],
    include: ['src/**/*.test.{ts,tsx}', 'tests/**/*.test.{ts,tsx}', 'mcp-server/**/*.test.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      all: false,
      exclude: [
        'node_modules/',
        'src/test/',
        'tests/**/*.spec.{ts,tsx}',
        'scripts/',
        'cli/',
        'docs/',
        'mcp-server/index.ts',
        'packages/readstat-wasm/dist/',
        'packages/readstat-wasm/scripts/',
        'packages/readstat-wasm/ts/index.ts',
        'playwright.config.ts',
        'vite.config.ts',
        'vitest.config.ts',
        '*.config.{js,cjs,mjs,ts}',
        'test_*.{js,mjs,ts}',
        'src/components/charts/',
        'src/components/overlays/',
        'src/engine/webr/',
        'src/core/export/chartBuilder.ts',
        'src/core/export/resolveThemeColors.ts',
        'src/core/export/types.ts',
        'src/features/',
        'src/hooks/',
        'src/services/EngineProxy.ts',
        'src/services/duckDbArrow.ts',
        'src/services/duckdbBundles.ts',
        'src/store/slices/',
        '**/*.d.ts',
        'dist/',
      ],
      thresholds: {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
      },
    },
  },
});
