"""Build SBT-001 Turn-4 deterministic reference analyses and findings."""
from __future__ import annotations
import json, math
from pathlib import Path
import numpy as np, pandas as pd
from scipy.stats import norm
ROOT=Path(__file__).resolve().parents[3]; PROJ=ROOT/'evals/research_quality/projects/synthetic/SBT-001'; OUT=PROJ/'reference'/'analysis'; OUT.mkdir(parents=True,exist_ok=True)
B=['northstar','pulse','mosaic','lumen','harbour']; LOW_BASE=50; waves={w:pd.read_csv(PROJ/'raw'/f'wave_{w:02d}.csv') for w in range(1,6)}
def wp(d,v,m=None,weighted=True):
 ok=d[v].isin([0,1]); ok=ok if m is None else ok&m; x=d.loc[ok]; y=x[v].astype(float).to_numpy(); wt=x.wt_final.to_numpy() if weighted else np.ones(len(x)); p=float(np.average(y,weights=wt)); ess=float(wt.sum()**2/np.square(wt).sum()); se=math.sqrt(max(p*(1-p)/ess,0)); return {'estimate':p,'unweightedBase':int(len(x)),'weightedBase':float(wt.sum()),'ess':ess,'se':se,'ci95':[max(0,p-1.96*se),min(1,p+1.96*se)]}
def wm(d,v,m):
 ok=d[v].between(0,10)&m; x=d.loc[ok]; y=x[v].astype(float).to_numpy(); wt=x.wt_final.to_numpy(); mu=float(np.average(y,weights=wt)); ess=float(wt.sum()**2/np.square(wt).sum()); va=float(np.average((y-mu)**2,weights=wt)); se=math.sqrt(va/ess); return {'estimate':mu,'unweightedBase':int(len(x)),'weightedBase':float(wt.sum()),'ess':ess,'se':se,'ci95':[mu-1.96*se,mu+1.96*se]}
def nps(d,b):
 m=(d.S8_current_provider==b)&d.E2_nps.between(0,10); x=d.loc[m]; wt=x.wt_final.to_numpy(); s=np.where(x.E2_nps>=9,1,np.where(x.E2_nps<=6,-1,0)); mu=float(np.average(s,weights=wt)); ess=float(wt.sum()**2/np.square(wt).sum()); se=float(100*np.sqrt(max(np.average(s*s,weights=wt)-mu*mu,0)/ess)); est=100*mu; return {'estimate':est,'unweightedBase':int(len(x)),'weightedBase':float(wt.sum()),'ess':ess,'se':se,'ci95':[est-1.96*se,est+1.96*se]}
def df(a,b):
 de=b['estimate']-a['estimate']; se=math.sqrt(a['se']**2+b['se']**2); z=de/se if se else 0.; return {'difference':de,'se':se,'z':z,'pValue':float(2*norm.sf(abs(z))),'ci95':[de-1.96*se,de+1.96*se]}
def rec(i,t,metric,u,w,res,cw=None,comp=None,tags=None):
 x={'analysisId':i,'analysisType':t,'metric':metric,'universe':u,'wave':w,'weight':'wt_final','result':res,'tags':tags or []};
 if cw is not None:x.update({'comparisonWave':cw,'comparison':comp})
 return x
R=[]
for w,d in waves.items():
 for b in B:
  R.append(rec(f'AWARE_{b.upper()}_W{w}','proportion',f'A2_{b}','all eligible completes',w,wp(d,f'A2_{b}'),tags=['funnel','awareness',b])); td=d.assign(_c=np.where(d[f'F2_{b}'].eq(1),1,0),_u=d.S8_current_provider.eq(b).astype(int),_p=d.F3_preference.eq(b).astype(int)); R.append(rec(f'CONSID_TOTAL_{b.upper()}_W{w}','proportion',f'consideration_total:{b}','all eligible completes; unaware count as not considering',w,wp(td,'_c'),tags=['funnel','consideration',b])); R.append(rec(f'USAGE_{b.upper()}_W{w}','proportion',f'current_provider:{b}','all eligible completes',w,wp(td,'_u'),tags=['funnel','usage',b])); R.append(rec(f'PREF_{b.upper()}_W{w}','proportion',f'preference:{b}','all eligible completes',w,wp(td,'_p'),tags=['funnel','preference',b]))
for weighted,label in [(True,'WEIGHTED'),(False,'UNWEIGHTED')]:
 a=wp(waves[2],'F2_pulse',weighted=weighted); b=wp(waves[3],'F2_pulse',weighted=weighted); R.append(rec(f'PULSE_CONSID_W2_W3_{label}','wave_change','F2_pulse','prompted-aware Pulse respondents',3,b,2,df(a,b),['pulse_campaign','planned',label.lower()]))
for seg in ['18_34','35_plus']:
 m2=waves[2].S1_age.isin(['18-24','25-34']); m3=waves[3].S1_age.isin(['18-24','25-34']); m2=m2 if seg=='18_34' else ~m2; m3=m3 if seg=='18_34' else ~m3; a=wp(waves[2],'F2_pulse',m2); b=wp(waves[3],'F2_pulse',m3); R.append(rec(f'PULSE_CONSID_{seg}_W2_W3','wave_change','F2_pulse',f'prompted-aware Pulse; {seg}',3,b,2,df(a,b),['pulse_campaign','segment']))
for w in [2,3]:R.append(rec(f'PULSE_INNOVATION_W{w}','proportion','I_pulse_innovative','Pulse familiarity >=3; DK excluded',w,wp(waves[w],'I_pulse_innovative'),tags=['brand_image','pulse_campaign']))
a=wp(waves[2],'I_pulse_innovative'); b=wp(waves[3],'I_pulse_innovative'); R.append(rec('PULSE_INNOVATION_W2_W3','wave_change','I_pulse_innovative','Pulse familiarity >=3; DK excluded',3,b,2,df(a,b),['planned','brand_image']))
for w in [3,4,5]:
 d=waves[w]; y=d.S1_age.isin(['18-24','25-34']); R.append(rec(f'PULSE_CAMPAIGN_RECOG_18_34_W{w}','proportion','M3_pulse_campaign_recognition','18-34 eligible completes',w,wp(d,'M3_pulse_campaign_recognition',y),tags=['marketing'])); R.append(rec(f'PULSE_CAMPAIGN_RECOG_35P_W{w}','proportion','M3_pulse_campaign_recognition','35+ eligible completes',w,wp(d,'M3_pulse_campaign_recognition',~y),tags=['marketing']))
for w in [3,4,5]:
 d=waves[w]; c=d.S8_current_provider.eq('northstar'); R += [rec(f'NORTHSTAR_NPS_W{w}','nps','E2_nps','current Northstar customers',w,nps(d,'northstar'),tags=['northstar','cx']),rec(f'NORTHSTAR_SAT_W{w}','mean','E1_satisfaction','current Northstar customers',w,wm(d,'E1_satisfaction',c),tags=['northstar','cx']),rec(f'NORTHSTAR_PROBLEM_W{w}','proportion','E3_problem','current Northstar customers',w,wp(d,'E3_problem',c),tags=['northstar','cx']),rec(f'NORTHSTAR_RELIABILITY_W{w}','proportion','I_northstar_reliable','Northstar familiarity >=3; DK excluded',w,wp(d,'I_northstar_reliable'),tags=['northstar','image']),rec(f'NORTHSTAR_AWARE_W{w}','proportion','A2_northstar','all eligible completes',w,wp(d,'A2_northstar'),tags=['northstar','awareness'])]
funcs={'NPS':lambda d:nps(d,'northstar'),'SAT':lambda d:wm(d,'E1_satisfaction',d.S8_current_provider.eq('northstar')),'PROBLEM':lambda d:wp(d,'E3_problem',d.S8_current_provider.eq('northstar')),'RELIABILITY':lambda d:wp(d,'I_northstar_reliable'),'AWARE':lambda d:wp(d,'A2_northstar')}
for met,fn in funcs.items():
 for aw,bw in [(3,4),(4,5)]:
  a=fn(waves[aw]); b=fn(waves[bw]); R.append(rec(f'NORTHSTAR_{met}_W{aw}_W{bw}','wave_change',met.lower(),'metric-specific approved universe',bw,b,aw,df(a,b),['northstar','planned']))
for w,d in waves.items():
 y=d.S1_age.isin(['18-24','25-34']); R.append(rec(f'HARBOUR_CONSID_18_34_W{w}','proportion','F2_harbour','prompted-aware Harbour respondents aged 18-34',w,wp(d,'F2_harbour',y),tags=['harbour','trend']))
a=wp(waves[1],'F2_harbour',waves[1].S1_age.isin(['18-24','25-34'])); b=wp(waves[5],'F2_harbour',waves[5].S1_age.isin(['18-24','25-34'])); R.append(rec('HARBOUR_CONSID_18_34_W1_W5','wave_change','F2_harbour','prompted-aware Harbour respondents aged 18-34',5,b,1,df(a,b),['harbour','trend','planned']))
for w in [3,4,5]:
 d=waves[w]; m=d.S2_gender.eq('Non-binary/another identity'); td=d.assign(_c=np.where(d.F2_mosaic.eq(1),1,0)); R.append(rec(f'MOSAIC_CONSID_NB_W{w}','proportion','consideration_total:mosaic','non-binary/another identity respondents',w,wp(td,'_c',m),tags=['mosaic','low_base','do_not_promote']))
by={x['analysisId']:x for x in R}; pp=lambda x:100*x
def F(i,t,refs,s,prom,rel,mat='medium',c=None):return {'findingId':i,'claimType':t,'analysisRefs':refs,'statement':s,'promotionStatus':prom,'editorialRelevance':rel,'materiality':mat,'caveats':c or []}
pw=by['PULSE_CONSID_W2_W3_WEIGHTED']['comparison']; pu=by['PULSE_CONSID_W2_W3_UNWEIGHTED']['comparison']; ni=by['NORTHSTAR_NPS_W3_W4']['comparison']; na=by['NORTHSTAR_AWARE_W3_W4']['comparison']; h=by['HARBOUR_CONSID_18_34_W1_W5']['comparison']; m=by['MOSAIC_CONSID_NB_W4']['result']
findings=[F('F_PULSE_CONSID_UP','trend',['PULSE_CONSID_W2_W3_WEIGHTED'],f"Pulse consideration among prompted-aware respondents increased {pp(pw['difference']):.1f} percentage points from Wave 2 to Wave 3 on the approved weighted estimate.",'headline_candidate',{'BRIEF_PULSE_CMO':'high','BRIEF_CATEGORY_BOARD':'high'},'high',['Observed tracker change; do not claim the campaign caused the increase.']),F('F_PULSE_WEIGHT_TRAP','caveat',['PULSE_CONSID_W2_W3_WEIGHTED','PULSE_CONSID_W2_W3_UNWEIGHTED'],f"The unweighted Pulse movement ({pp(pu['difference']):.1f}pp) overstates the weighted movement ({pp(pw['difference']):.1f}pp).",'supporting',{'BRIEF_PULSE_CMO':'high','BRIEF_CATEGORY_BOARD':'medium'},'high'),F('F_NORTHSTAR_NPS_DROP','trend',['NORTHSTAR_NPS_W3_W4'],f"Northstar NPS among current customers fell {abs(ni['difference']):.1f} points from Wave 3 to Wave 4.",'headline_candidate',{'BRIEF_NORTHSTAR_CX':'high','BRIEF_CATEGORY_BOARD':'high'},'high'),F('F_NORTHSTAR_AWARE_RESILIENT','caveat',['NORTHSTAR_AWARE_W3_W4'],f"Northstar prompted awareness changed only {pp(na['difference']):+.1f}pp from Wave 3 to Wave 4 while customer experience deteriorated.",'supporting',{'BRIEF_NORTHSTAR_CX':'high','BRIEF_CATEGORY_BOARD':'high'},'medium',['Small movement is not an equivalence test.']),F('F_HARBOUR_YOUTH_DECLINE','trend',['HARBOUR_CONSID_18_34_W1_W5'],f"Harbour consideration among prompted-aware 18–34s declined {abs(pp(h['difference'])):.1f} percentage points between Wave 1 and Wave 5.",'headline_candidate',{'BRIEF_CATEGORY_BOARD':'high'},'high'),F('F_MOSAIC_LOWBASE_SPIKE','caveat',['MOSAIC_CONSID_NB_W3','MOSAIC_CONSID_NB_W4','MOSAIC_CONSID_NB_W5'],f"Mosaic has a dramatic point estimate among non-binary respondents, but the Wave 4 base is only {m['unweightedBase']}; do not promote it.",'do_not_promote',{'BRIEF_CATEGORY_BOARD':'none'},'low',['Low base; unstable estimate.'])]
(OUT/'analysis_results.json').write_text(json.dumps({'projectId':'SBT-001','version':'turn4-v1','lowBaseThreshold':LOW_BASE,'analyses':R},indent=2),encoding='utf-8'); (OUT/'findings.json').write_text(json.dumps({'projectId':'SBT-001','version':'turn4-v1','findings':findings},indent=2),encoding='utf-8')
summary={'analysisCount':len(R),'findingCount':len(findings),'hardChecks':{'allResultsHaveBases':all('unweightedBase' in x['result'] for x in R),'allFindingsHaveAnalysisRefs':all(all(r in by for r in f['analysisRefs']) for f in findings),'mosaicLowBasePreserved':m['unweightedBase']<LOW_BASE},'keyMetrics':{'pulseWeightedChangePp':pp(pw['difference']),'pulseUnweightedChangePp':pp(pu['difference']),'northstarNpsChange':ni['difference'],'northstarAwarenessChangePp':pp(na['difference']),'harbourYouthChangePp':pp(h['difference']),'mosaicWave4Base':m['unweightedBase']}}
summary['passed']=all(summary['hardChecks'].values()); (OUT/'validation_summary.json').write_text(json.dumps(summary,indent=2),encoding='utf-8'); print(json.dumps(summary,indent=2))
