/**
 * R Parity Tests
 *
 * Validates Velocity's statistical output against R reference fixtures.
 * R's `survey` package is the academic gold standard for weighted survey
 * statistics. Fixtures were pre-generated by running:
 *
 *   Rscript validation/r/generate_ground_truth.R
 *
 * and are committed to tests/golden/expected/r_*.json so CI has no R
 * dependency.
 *
 * Column-name note: ReadStat-WASM (used by Velocity in Node.js) parses SPSS
 * files with LOWERCASE column names (sex, age, marital, taxspend, etc.).
 * DuckDB is case-insensitive so categorical tests pass with either case, but
 * measure-variable auto-promotion requires the exact lowercase id for context
 * lookup (tests 4 & 5 use lowercase). R's haven also returns lowercase names.
 *
 * WVS Wave 7 tests are .todo because ReadStat-WASM fails to parse the file
 * ("Levels read error. Magic value Expected: 4 Actual: 0"). The R fixtures
 * are committed so parity testing can start immediately when the fix lands.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import { DuckDBNodeAdapter } from '../../src/adapters/DuckDBNodeAdapter';
import { runCrosstab } from '../../src/core/analysis/crosstabRunner';
import { Variable, VariableSet } from '../../src/types';

const SAV_DIR  = resolve(__dirname, '../../test_data');
const EXPECTED = resolve(__dirname, 'expected');

// ---------------------------------------------------------------------------
// Helpers (mirrors golden.test.ts)
// ---------------------------------------------------------------------------

function loadExpected(name: string): any {
  const path = resolve(EXPECTED, name);
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, 'utf-8'));
}

function sortRows(rows: any[]): any[] {
  return [...rows].sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b)));
}

function expectCloseDeep(actual: any, expected: any, tolerance = 1e-6): void {
  if (typeof expected === 'number' && typeof actual === 'number') {
    expect(actual).toBeCloseTo(expected, -Math.log10(tolerance));
    return;
  }
  if (Array.isArray(expected)) {
    expect(Array.isArray(actual)).toBe(true);
    expect(actual.length).toBe(expected.length);
    for (let i = 0; i < expected.length; i++) {
      expectCloseDeep(actual[i], expected[i], tolerance);
    }
    return;
  }
  if (expected !== null && typeof expected === 'object') {
    expect(typeof actual).toBe('object');
    for (const key of Object.keys(expected)) {
      expectCloseDeep(actual[key], expected[key], tolerance);
    }
    return;
  }
  expect(actual).toEqual(expected);
}

function expectCloseDeepFromFixture(
  actual: any,
  fixtureName: string,
  tolerance = 1e-6,
): void {
  const expected = loadExpected(fixtureName);
  expect(expected, `Fixture not found: ${fixtureName}`).not.toBeNull();
  expectCloseDeep(actual, expected, tolerance);
}

// ---------------------------------------------------------------------------
// sleep.sav (271 rows, no survey weight)
// NOTE: The WEIGHT column in sleep.sav is respondent body weight, NOT a
//       survey weight. All sleep.sav tests are unweighted.
// ---------------------------------------------------------------------------

describe('R Parity: sleep.sav', () => {
  let db: DuckDBNodeAdapter;
  let vars: Record<string, Variable>;
  let varSets: Record<string, VariableSet>;

  beforeAll(async () => {
    db = await DuckDBNodeAdapter.create();
    const result = await db.loadSav(resolve(SAV_DIR, 'sleep.sav'));
    vars    = Object.fromEntries(result.variables.map(v => [v.id, v]));
    varSets = Object.fromEntries(result.variableSets.map(vs => [vs.id, vs]));
  }, 30_000);

  afterAll(async () => { await db.close(); });

  // ── Test 1 ────────────────────────────────────────────────────────────────
  it('Test 1 – unweighted frequency: SEX', async () => {
    const results = await runCrosstab(db, {
      rowVars: ['SEX'], colVar: null, weightVar: null, filters: [],
    }, { variables: vars, variableSets: varSets });

    expectCloseDeepFromFixture(sortRows(results.rows), 'r_sleep_freq_sex.json');
  });

  // ── Tests 2 & 3 ───────────────────────────────────────────────────────────
  // Share one runCrosstab call: rows → test 2, tableStats.chiSquare → test 3
  let crosstabMARITAL_SEX: Awaited<ReturnType<typeof runCrosstab>>;

  it('Test 2 – unweighted crosstab: MARITAL x SEX', async () => {
    crosstabMARITAL_SEX = await runCrosstab(db, {
      rowVars: ['MARITAL'], colVar: 'SEX', weightVar: null, filters: [],
    }, { variables: vars, variableSets: varSets });

    expectCloseDeepFromFixture(
      sortRows(crosstabMARITAL_SEX.rows),
      'r_sleep_crosstab_marital_sex.json',
    );
  });

  it('Test 3 – chi-square: MARITAL x SEX', async () => {
    // Re-run if test 2 didn't run first (test isolation)
    if (!crosstabMARITAL_SEX) {
      crosstabMARITAL_SEX = await runCrosstab(db, {
        rowVars: ['MARITAL'], colVar: 'SEX', weightVar: null, filters: [],
      }, { variables: vars, variableSets: varSets });
    }
    const chiSq = crosstabMARITAL_SEX.tableStats?.chiSquare;
    expect(chiSq, 'tableStats.chiSquare should be present').toBeDefined();
    expectCloseDeepFromFixture(chiSq!, 'r_sleep_chisq_marital_sex.json', 1e-4);
  });

  // ── Test 4 ────────────────────────────────────────────────────────────────
  // 'age' (lowercase) is required so context.variables['age'] resolves and
  // auto-promotes AGE to measureVar. measureLabel = vars['age'].label = "age",
  // so rowKey_0 = "age" in the output.
  it('Test 4 – unweighted mean/stddev: AGE by SEX', async () => {
    const results = await runCrosstab(db, {
      rowVars: ['age'], colVar: 'sex', weightVar: null, filters: [],
    }, { variables: vars, variableSets: varSets });

    expectCloseDeepFromFixture(sortRows(results.rows), 'r_sleep_mean_age_sex.json');
  });

  // ── Test 5 ────────────────────────────────────────────────────────────────
  it('Test 5 – unweighted mean/stddev: AGE by MARITAL', async () => {
    const results = await runCrosstab(db, {
      rowVars: ['age'], colVar: 'marital', weightVar: null, filters: [],
    }, { variables: vars, variableSets: varSets });

    expectCloseDeepFromFixture(sortRows(results.rows), 'r_sleep_mean_age_marital.json');
  });
});

// ---------------------------------------------------------------------------
// bsa93.sav (2945 rows, survey weight: WTFACTOR)
// ---------------------------------------------------------------------------

describe('R Parity: bsa93.sav', () => {
  let db: DuckDBNodeAdapter;
  let vars: Record<string, Variable>;
  let varSets: Record<string, VariableSet>;

  beforeAll(async () => {
    db = await DuckDBNodeAdapter.create();
    const result = await db.loadSav(
      resolve(SAV_DIR, 'British Social Attitudes Survey', 'bsa93.sav'),
    );
    vars    = Object.fromEntries(result.variables.map(v => [v.id, v]));
    varSets = Object.fromEntries(result.variableSets.map(vs => [vs.id, vs]));
  }, 30_000);

  afterAll(async () => { await db.close(); });

  // ── Test 6 ────────────────────────────────────────────────────────────────
  it('Test 6 – unweighted frequency: TAXSPEND', async () => {
    const results = await runCrosstab(db, {
      rowVars: ['TAXSPEND'], colVar: null, weightVar: null, filters: [],
    }, { variables: vars, variableSets: varSets });

    expectCloseDeepFromFixture(sortRows(results.rows), 'r_bsa93_freq_taxspend.json');
  });

  // ── Test 7 ────────────────────────────────────────────────────────────────
  it('Test 7 – weighted frequency: TAXSPEND by WTFACTOR', async () => {
    const results = await runCrosstab(db, {
      rowVars: ['TAXSPEND'], colVar: null, weightVar: 'WTFACTOR', filters: [],
    }, { variables: vars, variableSets: varSets });

    expectCloseDeepFromFixture(
      sortRows(results.rows),
      'r_bsa93_wfreq_taxspend.json',
      1e-4,
    );
  });

  // ── Tests 8 & 10 ──────────────────────────────────────────────────────────
  let crosstabNHSSAT_VERSION: Awaited<ReturnType<typeof runCrosstab>>;

  it('Test 8 – unweighted crosstab: NHSSAT x VERSION', async () => {
    crosstabNHSSAT_VERSION = await runCrosstab(db, {
      rowVars: ['NHSSAT'], colVar: 'VERSION', weightVar: null, filters: [],
    }, { variables: vars, variableSets: varSets });

    expectCloseDeepFromFixture(
      sortRows(crosstabNHSSAT_VERSION.rows),
      'r_bsa93_crosstab_nhssat_version.json',
    );
  });

  // ── Test 9 ────────────────────────────────────────────────────────────────
  it('Test 9 – weighted crosstab: NHSSAT x VERSION by WTFACTOR', async () => {
    const results = await runCrosstab(db, {
      rowVars: ['NHSSAT'], colVar: 'VERSION', weightVar: 'WTFACTOR', filters: [],
    }, { variables: vars, variableSets: varSets });

    expectCloseDeepFromFixture(
      sortRows(results.rows),
      'r_bsa93_wcrosstab_nhssat_version.json',
      1e-4,
    );
  });

  // ── Test 10 ───────────────────────────────────────────────────────────────
  it('Test 10 – chi-square: NHSSAT x VERSION', async () => {
    if (!crosstabNHSSAT_VERSION) {
      crosstabNHSSAT_VERSION = await runCrosstab(db, {
        rowVars: ['NHSSAT'], colVar: 'VERSION', weightVar: null, filters: [],
      }, { variables: vars, variableSets: varSets });
    }
    const chiSq = crosstabNHSSAT_VERSION.tableStats?.chiSquare;
    expect(chiSq, 'tableStats.chiSquare should be present').toBeDefined();
    expectCloseDeepFromFixture(chiSq!, 'r_bsa93_chisq_nhssat_version.json', 1e-4);
  });

  // ── Test 11 ───────────────────────────────────────────────────────────────
  it('Test 11 – weighted frequency: DOLE by WTFACTOR', async () => {
    const results = await runCrosstab(db, {
      rowVars: ['DOLE'], colVar: null, weightVar: 'WTFACTOR', filters: [],
    }, { variables: vars, variableSets: varSets });

    expectCloseDeepFromFixture(
      sortRows(results.rows),
      'r_bsa93_wfreq_dole.json',
      1e-4,
    );
  });

  // ── Test 12 ───────────────────────────────────────────────────────────────
  // Kish's ESS = weightedCount² / sumSqWeights — validated via fixture fields
  it('Test 12 – ESS per group: VERSION with WTFACTOR', async () => {
    const results = await runCrosstab(db, {
      rowVars: ['VERSION'], colVar: null, weightVar: 'WTFACTOR', filters: [],
    }, { variables: vars, variableSets: varSets });

    expectCloseDeepFromFixture(
      sortRows(results.rows),
      'r_bsa93_wfreq_version_ess.json',
      1e-4,
    );
  });
});

// ---------------------------------------------------------------------------
// WVS Wave 7 (97,220 rows) — BLOCKED by jsavvy parsing bug
//
// jsavvy fails on this file: "Levels read error. Magic value Expected: 4
// Actual: 0". R fixtures are committed so tests can be activated immediately
// when the parsing bug is fixed (change .todo → plain it).
// ---------------------------------------------------------------------------

describe('R Parity: WVS Wave 7 (todo — jsavvy parsing bug)', () => {
  it.todo('Test 13 – unweighted frequency: Q46 (happiness)');
  it.todo('Test 14 – weighted frequency: Q46 by W_WEIGHT');
  it.todo('Test 15 – weighted crosstab: Q1 x Q260 by W_WEIGHT');
});
